name: New feature
title: "🚀[FEATURE] <title>"
description: Suggest a new feature for this project
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to properly describe the new feature you are suggesting.

        **Contribution Guidelines**

        - If you want to work on an issue, please let us know in a comment below.
        - Do not begin work on the issue unless it has been assigned to you.
        - If you do not respond in 3 days, the issue may be reassigned to someone else.
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      placeholder: I'd like to have this feature
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Why do you think this feature should be implemented?
      placeholder: It would be useful for this reason
  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: |
        Add any other context or screenshots about the feature request here.
  - type: checkboxes
    id: checks
    attributes:
      label: Extra fields
      options:
        - label: I have used the search function to check if an issue already exists
          required: true
        - label: I'd like to work on this issue
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! Let's see together if it can be implemented.
