name: Format code before push to default branches

on:
  push:
    branches:
      - truth-redefined-again
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.KS_PAT }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm format
      - name: Configure SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KS_SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.KS_SSH_PUBLIC_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/koss-service
          echo "$SSH_PUBLIC_KEY" > ~/.ssh/koss-service.pub
          chmod 600 ~/.ssh/koss-service
          chmod 600 ~/.ssh/koss-service.pub
      - name: Push
        run: |
          git config --local user.email "admin@kossiitkgp.org"
          git config --local user.name "koss-service"
          git config gpg.format ssh
          git config user.signingkey ~/.ssh/koss-service.pub
          git commit -S -am "Apply prettier formatting"
          git push
